spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0


zuul:
  prefix: /api
  routes:
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301

